name: python compile(Linux&Windows)

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Compile exe
        run: |
          pyinstaller -n copymanga-download -F main.py 
      - name : upload exe
        uses: actions/upload-artifact@master
        with:
          name: copymanga-download-Linux
          path: dist/copymanga-download
  
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path -path "requirements.txt" -PathType Leaf) {
            pip install -r requirements.txt
          }
      - name: Compile exe
        run: |
          pyinstaller -n copymanga-download -F main.py 
      - name : upload exe
        uses: actions/upload-artifact@master
        with:
          name: copymanga-download-windows
          path: dist/copymanga-download.exe
