name: python compile(Linux&Windows)

on:
  release:
    types: [published]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Compile exe
        run: |
          pyinstaller -n copymanga-download -F main.py 
      - name : upload exe
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: copymanga-download-Linux
          path: ${{ github.workspace }}/dist/
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Compile exe
        run: |
          pyinstaller -n copymanga-download -F main.py 
      - name : upload exe
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: copymanga-download-windows
          path: ${{ github.workspace }}/dist/
